version: "3"
services:
  supercut:
    container_name: node-express-rest
    image: pedrotti/node-express:dev
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      # DB_CONNECTION_URL: 'mysql://root:root@127.0.0.1:3306/app' # Migrations connector
      DB_DIALECT: 'mysql'
      DB_HOST: '127.0.0.1'
      DB_PORT: '3306'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'root'
      DB_NAME: 'app'
    network_mode: bridge