version: "3"
services:
  node:
    image: pedrotti/node-express:dev
    container_name: node-api
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    ports:
      - "8080:3000"
    environment:
      DB_CONNECTION_URL: 'postgres://postgres:postgres@dbhost:5432/app'
      DB_DIALECT: 'postgres'
      DB_HOST: 'dbhost'
      DB_PORT: '5432'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'postgres'
      DB_NAME: 'app'
      GITHUB_TOKEN: '?????????????????????????????????????????????????????????????????????????????????????????????'
      JWT_SECRET: '????????????????????????????????????????????????????????????????'
    links:
      - postgres:dbhost
    network_mode: bridge
  postgres:
    image: postgres:15-alpine
    container_name: node-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - 5432:5432
    network_mode: bridge