service: node-express-rest

plugins:
  - serverless-scriptable-plugin
  - serverless-sequelize-migrations
  - serverless-offline

package:
  exclude:
    # - node_modules/*
    - migrations/*
    - scripts/**
    - README.md
    - package.json
    - package-lock.json

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    # DB_CONNECTION_URL: 'mysql://root:root@127.0.0.1:3306/app' # Migrations connector
    DB_DIALECT: 'mysql'
    DB_HOST: '127.0.0.1'
    DB_PORT: '3306'
    DB_USERNAME: 'root'
    DB_PASSWORD: 'root'
    DB_NAME: 'app'
    JWT_SECRET: '5f04828ed29602f8dfe1822d20ba58ff10aa4828b8e986e357658423cfa971f1'

functions:
  main:
    name: 'node-express-rest'
    timeout: 30
    handler: ./lambda.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'